// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdsUmCYr0N36rNGITkpi3S4g-Qyj8Dp0k',
    appId: '1:613280203881:web:7ac36f6b174fba686a0ef8',
    messagingSenderId: '613280203881',
    projectId: 'flashchat-5ad82',
    authDomain: 'flashchat-5ad82.firebaseapp.com',
    storageBucket: 'flashchat-5ad82.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVNFq8fjX6wphOgVuJZ6iT-VTDE3uqqYc',
    appId: '1:613280203881:android:82392dfb4d5d33076a0ef8',
    messagingSenderId: '613280203881',
    projectId: 'flashchat-5ad82',
    storageBucket: 'flashchat-5ad82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5BmBcK3jAiC1l1eABwDZU_Uicr1AzvYE',
    appId: '1:613280203881:ios:41ca9b37ff81c0d26a0ef8',
    messagingSenderId: '613280203881',
    projectId: 'flashchat-5ad82',
    storageBucket: 'flashchat-5ad82.firebasestorage.app',
    iosBundleId: 'com.mjnbukhari.flashchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5BmBcK3jAiC1l1eABwDZU_Uicr1AzvYE',
    appId: '1:613280203881:ios:41ca9b37ff81c0d26a0ef8',
    messagingSenderId: '613280203881',
    projectId: 'flashchat-5ad82',
    storageBucket: 'flashchat-5ad82.firebasestorage.app',
    iosBundleId: 'com.mjnbukhari.flashchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdsUmCYr0N36rNGITkpi3S4g-Qyj8Dp0k',
    appId: '1:613280203881:web:fcd3c72adaf400616a0ef8',
    messagingSenderId: '613280203881',
    projectId: 'flashchat-5ad82',
    authDomain: 'flashchat-5ad82.firebaseapp.com',
    storageBucket: 'flashchat-5ad82.firebasestorage.app',
  );
}
